#!/bin/bash

curl -O "https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz" && \
tar zxf "swiftly-$(uname -m).tar.gz" && \
./swiftly init --quiet-shell-followup --skip-install && \
. ~/.local/share/swiftly/env.sh && \
hash -r
